# Generated by Django 2.2.7 on 2019-12-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191205_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заглавие письма')),
                ('email_destination', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='Тело письма')),
                ('sending_time', models.DateTimeField(blank=True, verbose_name='Время отправки')),
            ],
        ),
    ]
