# Generated by Django 2.2.7 on 2019-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191205_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заглавие письма'),
        ),
    ]
